services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu

    volumes:
      - .:/workspaces/capstone-rag:cached
      - /var/run/docker.sock:/var/run/docker-host.sock

    command: sleep infinity

    depends_on:
      db:
        condition: service_healthy